Server:
  port: 8000
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive # 스프링 웹플럭스 사용
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS
      routes:
#        - id: feed-swagger
#          uri: lb://FEED-SERVICE
#          predicates:
#            - Path=/feed-service/swagger-ui.html
#            - Path=/feed-service/webjars/**
#          filters:
#            - StripPrefix=1
#        - id: feed-service-docs
#          uri: lb://FEED-SERVICE
#          predicates:
#            - Path=/feed-service/v3/api-docs
#          filters:
#            - StripPrefix=1

        - id: feed-service
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/feed-service/**
          filters:
            - StripPrefix=1

#        JWT 이 필요한 경우
        - id: feed-service
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka/


springdoc:
  api-docs:
    path: /v3/api-docs  # API 문서 경로
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

    urls:
      - url: "/feed-service/v3/api-docs"
        name: "Feed Service API"
#    servers:
#      - url: "http://localhost:8000/feed-service"  # Gateway에서 설정한 경로로 API 요청
#        description: "Gateway API"

jwt:
  secret: test
#jwt:
#    secret: ${JWT_SECRET_KEY}